version: '3.8'

services:
  # 1) PostgreSQL
  postgres:
    image: ankane/pgvector:latest
    container_name: searchright-psql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: searchright
      POSTGRES_PASSWORD: searchright
      POSTGRES_DB: searchright
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data

  # 2) FastAPI 애플리케이션
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: searchright-api
    depends_on:
      - postgres
    environment:
      # .env 파일에 OPENAI_API_KEY가 정의되어 있으면 자동으로 로드됩니다.
      DATABASE_URL: postgresql://searchright:searchright@postgres:5432/searchright
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "9000:9000"

  # 3) Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: searchright-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      TZ: Asia/Seoul
    depends_on:
      - api-service
      - postgres
